---  
- name: postgresql demo
  hosts: 192.168.29.224
  become: true
  vars:
    db_name: testdb
    backup_dir: "/var/lib/pgsql/backups"
  tasks:
    - name: Restore db
      postgresql_db:
        state: restore
        name: "{{ db_name }}"
        target: "{{ backup_dir }}/{{ db_name }}.gz"
      become: true
      become_user: postgres
